### ISSUE TITLE
Hello from another crawler in browser

### ISSUE THREAD

**Issue by nobodxbodon** [LeonardoCiaccio/Crawy#1]
Hi I just found your project. I did similar (kind of) with a very different approach in https://github.com/nobodxbodon/ChromeCrawlerWildSpider. I wonder if you have future roadmap for Crawy or GrabAnyMedia?

**Comment by LeonardoCiaccio** [comment]
Hi, yes i have a roadmap for GrabAnyMedia and Crawy, you like my project ?

Crawy for this moment work like bookmarklets without installation, GrabAnyMedia evolve in to client desktop when i found more fund :)

**Comment by nobodxbodon** [comment]
May I ask a few questions about Crawy?

- does it support crawling beyond current domain?
- is it fetching DOM content only?

I chose to use browser to render web page when crawling, as too many contents are rendered by JS these days, and I didn't want to use rendering engine like phantomjs.

**Comment by LeonardoCiaccio** [comment]
- Only current domain ( cross-browsing problems )

- Yes, content DOM ( fast and accurate )

**Comment by nobodxbodon** [comment]
Right. I chose to crawl in the much slower way because I wanted to overcome cross-domain issues and JS rendering. May I ask what you intend to use Crowy for? General-purpose crawling?

**Comment by LeonardoCiaccio** [comment]
You can use Crawy for grab all information in to domain, for example you can grab all links for video streaming, all images, any imformation you want
